### PR TITLE
Replace elm.vim with elm-vim

### PR DESCRIPTION
**Pull request by tennety**
- Elm-format support (needs elm-format installed: `npm install -g elm-format`)
- Docs (needs elm-oracle installed: `npm install -g elm-oracle`)
- Subprocess REPL

### CODE REVIEW

**Comment by nummi** [comment]
Will it cause issues if people do not have the node packages installed?

**Comment by tennety** [comment]
No, it just writes an error to the little command area in Vim. But who won't have elm-format installed?? ;)

**Comment by nummi** [comment]
What is Elm?

**Comment by nummi** [comment]
👍🏽

**Pull request merged**
